include { GRIFFIN_GC_AND_MAPPABILITY_CORRECTION } from './subworkflows/local/GRIFFIN_GC_AND_MAPPABILITY_CORRECTION.nf'

workflow GRIFFIN {
    GRIFFIN_GC_AND_MAPPABILITY_CORRECTION()

}

workflow {
    GRIFFIN()
}
